// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: emacsheadless.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdType int32

const (
	CmdType_DrawChar CmdType = 0
	CmdType_DrawLine CmdType = 1
)

// Enum value maps for CmdType.
var (
	CmdType_name = map[int32]string{
		0: "DrawChar",
		1: "DrawLine",
	}
	CmdType_value = map[string]int32{
		"DrawChar": 0,
		"DrawLine": 1,
	}
)

func (x CmdType) Enum() *CmdType {
	p := new(CmdType)
	*p = x
	return p
}

func (x CmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_emacsheadless_proto_enumTypes[0].Descriptor()
}

func (CmdType) Type() protoreflect.EnumType {
	return &file_emacsheadless_proto_enumTypes[0]
}

func (x CmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdType.Descriptor instead.
func (CmdType) EnumDescriptor() ([]byte, []int) {
	return file_emacsheadless_proto_rawDescGZIP(), []int{0}
}

type Cmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type CmdType `protobuf:"varint,1,opt,name=type,proto3,enum=headless.CmdType" json:"type,omitempty"`
}

func (x *Cmd) Reset() {
	*x = Cmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emacsheadless_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd) ProtoMessage() {}

func (x *Cmd) ProtoReflect() protoreflect.Message {
	mi := &file_emacsheadless_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd.ProtoReflect.Descriptor instead.
func (*Cmd) Descriptor() ([]byte, []int) {
	return file_emacsheadless_proto_rawDescGZIP(), []int{0}
}

func (x *Cmd) GetType() CmdType {
	if x != nil {
		return x.Type
	}
	return CmdType_DrawChar
}

var File_emacsheadless_proto protoreflect.FileDescriptor

var file_emacsheadless_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x6d, 0x61, 0x63, 0x73, 0x68, 0x65, 0x61, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68, 0x65, 0x61, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x22,
	0x2c, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x43, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x25, 0x0a,
	0x07, 0x43, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x72, 0x61, 0x77,
	0x43, 0x68, 0x61, 0x72, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x72, 0x61, 0x77, 0x4c, 0x69,
	0x6e, 0x65, 0x10, 0x01, 0x32, 0x3d, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x64, 0x6c, 0x65, 0x73, 0x73,
	0x12, 0x31, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0d, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6d, 0x64, 0x1a, 0x0d,
	0x2e, 0x68, 0x65, 0x61, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6d, 0x64, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emacsheadless_proto_rawDescOnce sync.Once
	file_emacsheadless_proto_rawDescData = file_emacsheadless_proto_rawDesc
)

func file_emacsheadless_proto_rawDescGZIP() []byte {
	file_emacsheadless_proto_rawDescOnce.Do(func() {
		file_emacsheadless_proto_rawDescData = protoimpl.X.CompressGZIP(file_emacsheadless_proto_rawDescData)
	})
	return file_emacsheadless_proto_rawDescData
}

var file_emacsheadless_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_emacsheadless_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_emacsheadless_proto_goTypes = []interface{}{
	(CmdType)(0), // 0: headless.CmdType
	(*Cmd)(nil),  // 1: headless.Cmd
}
var file_emacsheadless_proto_depIdxs = []int32{
	0, // 0: headless.Cmd.type:type_name -> headless.CmdType
	1, // 1: headless.Headless.SendMessage:input_type -> headless.Cmd
	1, // 2: headless.Headless.SendMessage:output_type -> headless.Cmd
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_emacsheadless_proto_init() }
func file_emacsheadless_proto_init() {
	if File_emacsheadless_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_emacsheadless_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emacsheadless_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emacsheadless_proto_goTypes,
		DependencyIndexes: file_emacsheadless_proto_depIdxs,
		EnumInfos:         file_emacsheadless_proto_enumTypes,
		MessageInfos:      file_emacsheadless_proto_msgTypes,
	}.Build()
	File_emacsheadless_proto = out.File
	file_emacsheadless_proto_rawDesc = nil
	file_emacsheadless_proto_goTypes = nil
	file_emacsheadless_proto_depIdxs = nil
}
